// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kDebugMode, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = kDebugMode
      ? FirebaseOptions(
          apiKey: 'AIzaSyBT-qw6ehRWxotSUmhOh7AUb6dNEgnjVMw',
          appId: '1:949494670699:web:6d595c7f8f54666ca6582e',
          messagingSenderId: '949494670699',
          projectId: 'cinemaguess-80df6',
          authDomain: 'cinemaguess-80df6.firebaseapp.com',
          storageBucket: 'cinemaguess-80df6.appspot.com',
          measurementId: 'G-PB8ZBDDNC1',
          databaseURL: 'https://cinemaguess-80df6-default-rtdb.firebaseio.com/')
      : FirebaseOptions(
          apiKey: "AIzaSyAnqcj1oym8663LyMUJl-DKHMaLPV4U4EI",
          authDomain: "cinemaguess-hapk.firebaseapp.com",
          projectId: "cinemaguess-hapk",
          storageBucket: "cinemaguess-hapk.appspot.com",
          messagingSenderId: "250391001271",
          appId: "1:250391001271:web:aa9342fc12e6a6d3c07532",
          databaseURL: 'https://cinemaguess-hapk-default-rtdb.firebaseio.com/',
          measurementId: "G-XTTZW5D720");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpH2qnHOv7YXAYFetSsGcKGdsF2MHqtlg',
    appId: '1:949494670699:android:79d2e0358368a9d8a6582e',
    messagingSenderId: '949494670699',
    projectId: 'cinemaguess-80df6',
    storageBucket: 'cinemaguess-80df6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFxDu5q7POFZnDjPagUADbqSMomnxlWiQ',
    appId: '1:949494670699:ios:627eba44cb7d1f52a6582e',
    messagingSenderId: '949494670699',
    projectId: 'cinemaguess-80df6',
    storageBucket: 'cinemaguess-80df6.appspot.com',
    iosClientId:
        '949494670699-60uo13hahbeeu6bqcd3md3v0uh5075al.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaGuess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFxDu5q7POFZnDjPagUADbqSMomnxlWiQ',
    appId: '1:949494670699:ios:627eba44cb7d1f52a6582e',
    messagingSenderId: '949494670699',
    projectId: 'cinemaguess-80df6',
    storageBucket: 'cinemaguess-80df6.appspot.com',
    iosClientId:
        '949494670699-60uo13hahbeeu6bqcd3md3v0uh5075al.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaGuess',
  );
}
